version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres-srv
    container_name: bookstore-postgres-container
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      app:

  adminer:
    image: adminer:latest
    restart: always
    hostname: adm-srv
    container_name: adminer-container
    environment:
      ADMINER_DEFAULT_SERVER: postgres-srv
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      app:

  bookstore:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    hostname: bookstore-srv
    container_name: bookstore-container
    environment:
      PORT: ':3000'
      DB_URL: 'postgres://postgres:postgres@postgres-srv:5432/bookstore?sslmode=disable'
      GIN_MODE: 'release'
      DEBUG: 'false'
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - postgres
    networks:
      app:

networks:
  app:
    name: book-store-network

volumes:
  postgres:
    name: bookstore-postgres
