#  https://github.com/HubSpot/prettier-maven-plugin

tabWidth: 2
endOfLine: lf
printWidth: 80
singleQuote: true
overrides:
  - files:
      - "*.java"
    options:
      endOfLine: lf
      tabWidth: 2
      printWidth: 100
      useTabs: true
      singleQuote: false
