debug: false
server:
  port: 3000
  servlet:
    context-path: /api
env:
  db: "bookstore"
  host: "localhost"
  port: "5432"
  user: "admin"
  password: "admin"
  #  postgres://admin:admin@localhost:5432/bookstore
  url: "postgresql://${env.host}:${env.port}/${env.db}"
spring:
  application:
    name: bookstore
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:${env.url}"
    username: ${env.user}
    password: ${env.password}
  jpa:
    database: postgresql
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgresPlusDialect
  flyway:
    enabled: true
    url: "jdbc:${env.url}"
    user: ${env.user}
    password: ${env.password}
    table: "migrations"
    baseline-on-migrate: true
    validate-on-migrate: true
    driver-class-name: org.postgresql.Driver
    sql-migration-separator: "-"
    sql-migration-prefix: "0000"
hibernate:
  dialect: org.hibernate.dialect.PostgresPlusDialect
  show-sql: true
  format-sql: true
  hbm2ddl:
    auto: update
  connection:
    url: "jdbc:${env.url}"
    username: ${env.user}
    password: ${env.password}
    driver-class: org.postgres.Driver
